# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'untitled1.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.5
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
# from PyQt5.QtWidgets import QFileDialog
#
# import sys
# import os
#
#
# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(777, 625)
#
#         self.label = QtWidgets.QPlainTextEdit(Form)
#         self.label.setGeometry(QtCore.QRect(70, 310, 631, 21))
#         self.label.setObjectName("label")
#
#         self.pushButton = QtWidgets.QPushButton(Form)
#         self.pushButton.setGeometry(QtCore.QRect(330, 240, 131, 23))
#         self.pushButton.setObjectName("pushButton")
#
#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)
#
#         self.pushButton.clicked.connect(self.getFileName)
#
#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         #self.label.setText(_translate("Form", "TextLabel"))
#         self.pushButton.setText(_translate("Form", "Выбор файла"))
#
#     def getFileName(self):
#         filename, filetype = QFileDialog.getOpenFileName(self,
#                                                          "Выбрать файл",
#                                                          ".",
#                                                          "Text Files(*.txt);;JPEG Files(*.jpeg);;\
#                                                          PNG Files(*.png);;GIF File(*.gif);;All Files(*)")
#         self.label.appendHtml("<br>Выбрали файл: <b>{}</b> <br> <b>{:*^54}</b>"
#                                       "".format(filename, filetype))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())

from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QFileDialog, QMainWindow

from PyQt5.QtGui import QFont
#
import sys
import os

class Form(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.plainTextEdit = QtWidgets.QPlainTextEdit()
        self.plainTextEdit.setFont(QFont('Arial', 11))


        self.getFileNameButton = QtWidgets.QPushButton("Открыть файл")
        self.getFileNameButton.clicked.connect(self.get_file_name)

        self.startWorkButton = QtWidgets.QPushButton("Начать обработку")
        self.startWorkButton.clicked.connect(self.start_work)

        self.file_name = ''




        layoutV = QtWidgets.QVBoxLayout()
        layoutV.addWidget(self.getFileNameButton)

        layoutV.addWidget(self.startWorkButton)


        layoutH = QtWidgets.QHBoxLayout()
        layoutH.addLayout(layoutV)
        layoutH.addWidget(self.plainTextEdit)

        centerWidget = QtWidgets.QWidget()
        centerWidget.setLayout(layoutH)
        self.setCentralWidget(centerWidget)

        self.resize(740, 480)
        self.setWindowTitle("PyQt5-QFileDialog")


    def get_file_name(self):
        filename, filetype = QFileDialog.getOpenFileName(self,
                                                         "Выбрать файл",
                                                         ".",
                                                         "wav file(*.wav);; Mp3 Files(*.Mp3);;\
                                                         All Files(*)")
        self.plainTextEdit.appendHtml("<br><b>{}</b> <br>"
                                      "".format(filename, filetype))


        self.file_name = filename

    def start_work(self):
        if self.file_name is not '':
            pass



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = Form()
    ex.show()
    sys.exit(app.exec_())
